"""create_draws_table

Revision ID: 8d12a471fd8f
Revises: 
Create Date: 2026-07-24 14:26:52.002549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d12a471fd8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('ball_1', sa.Integer(), nullable=False),
    sa.Column('ball_2', sa.Integer(), nullable=False),
    sa.Column('ball_3', sa.Integer(), nullable=False),
    sa.Column('ball_4', sa.Integer(), nullable=False),
    sa.Column('ball_5', sa.Integer(), nullable=False),
    sa.Column('ball_6', sa.Integer(), nullable=False),
    sa.Column('bonus_ball', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_date')
    )
    op.create_index(op.f('ix_draws_id'), 'draws', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draws_id'), table_name='draws')
    op.drop_table('draws')
    # ### end Alembic commands ###
